# Generated by Django 4.1.2 on 2022-11-12 21:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
